(define memories
  '((memory flash (address (#xf80000 . #xffffff)) (fill 0)
	    (section (LoCodeStorage #xf8f000)
		     (VectorStorage #xf8ffe0)
		     (HiCodeStorage1 (#xfd0000 . #xfdffff))
		     (HiCodeStorage2 (#xfe0000 . #xfeffff))
		     (HiCodeStorage3 (#xff0000 . #xffffff))))
    (memory DirectPage (address (#x00c000 . #x00c0ff))
            (section (registers ztiny)))
    (memory LoRAM (address (#x00c100 . #x00efff))
            (section stack data zdata data heap))
    (memory NearRAM1 (address (#x010000 . #x017fff))
            (section znear near))
    (memory NearRAM2 (address (#x018000 . #x01ffff))
            (section cnear))
    (memory FarRAM1 (address (#x020000 . #x02ffff))
            (section far huge))
    (memory FarRAM2 (address (#x030000 . #x03ffff))
            (section zfar zhuge ))
    (memory LoCode (address (#x00f000 . #x00ffdf)) (scatter-to LoCodeStorage)
            (section code cdata (jumptable #x00f000)))
    (memory Vector (address (#x00ffe0 . #x00ffff)) (scatter-to VectorStorage)
            (section (reset #xfffc)))
    (memory HiCode1 (address (#x3d0000 . #x3dffff)) (scatter-to HiCodeStorage1)
	    (section cfar switch data_init_table ifar farcode))
    (memory HiCode2 (address (#x3e0000 . #x3effff)) (scatter-to HiCodeStorage2)
	    (section cfar switch data_init_table ifar farcode))
    (memory HiCode3 (address (#x3f0000 . #x3fffff)) (scatter-to HiCodeStorage3)
	    (section cfar switch data_init_table ifar farcode))
    (block stack (size #x1000))
    (block heap (size #x1000))
    (base-address _DirectPageStart DirectPage 0)
    (base-address _NearBaseAddress NearRAM1   0)
))
